// ─── HerNest V2 Shared Components ────────────────────────────────
import React from "react";
import { T, F, SHADOWS } from "../../config/theme";

// ── Card ──────────────────────────────────────────────────────────
export function Card({
  children,
  style,
  onClick,
}: {
  children: React.ReactNode;
  style?: React.CSSProperties;
  onClick?: () => void;
}) {
  return (
    <div
      onClick={onClick}
      style={{
        background: T.ivory,
        borderRadius: 20,
        border: `1px solid ${T.linen}`,
        padding: "16px 18px",
        boxShadow: SHADOWS.sm,
        marginBottom: 12,
        cursor: onClick ? "pointer" : "default",
        ...style,
      }}
    >
      {children}
    </div>
  );
}

// ── HeroCard ──────────────────────────────────────────────────────
export function HeroCard({
  eyebrow,
  title,
  subtitle,
  children,
  color = T.esp,
}: {
  eyebrow?: string;
  title: string;
  subtitle?: string;
  children?: React.ReactNode;
  color?: string;
}) {
  return (
    <div
      style={{
        background: `linear-gradient(135deg, ${color} 0%, ${color}dd 100%)`,
        borderRadius: 24,
        padding: "22px 20px",
        marginBottom: 16,
        boxShadow: SHADOWS.lg,
      }}
    >
      {eyebrow && (
        <p style={{ fontFamily: F.sans, fontSize: 10, fontWeight: 600, letterSpacing: "0.16em", textTransform: "uppercase", color: "rgba(255,255,255,0.5)", margin: "0 0 8px" }}>
          {eyebrow}
        </p>
      )}
      <h2 style={{ fontFamily: F.serif, fontStyle: "italic", fontSize: 26, fontWeight: 500, color: "#fff", margin: "0 0 4px", lineHeight: 1.2 }}>
        {title}
      </h2>
      {subtitle && (
        <p style={{ fontFamily: F.sans, fontSize: 13, color: "rgba(255,255,255,0.65)", margin: "6px 0 0" }}>
          {subtitle}
        </p>
      )}
      {children}
    </div>
  );
}

// ── PageTitle ─────────────────────────────────────────────────────
export function PageTitle({ eyebrow, title }: { eyebrow?: string; title: string }) {
  return (
    <div style={{ marginBottom: 20, paddingTop: 4 }}>
      {eyebrow && (
        <p style={{ fontFamily: F.sans, fontSize: 10, fontWeight: 600, letterSpacing: "0.16em", textTransform: "uppercase", color: T.taupe, margin: "0 0 6px" }}>
          {eyebrow}
        </p>
      )}
      <h1 style={{ fontFamily: F.serif, fontStyle: "italic", fontSize: 32, fontWeight: 500, color: T.esp, margin: 0, lineHeight: 1.1 }}>
        {title}
      </h1>
    </div>
  );
}

// ── Pill ──────────────────────────────────────────────────────────
export function Pill({
  label,
  active,
  onClick,
  color,
}: {
  label: string;
  active?: boolean;
  onClick?: () => void;
  color?: string;
}) {
  return (
    <button
      onClick={onClick}
      style={{
        background: active ? (color || T.esp) : T.sand,
        color: active ? "#fff" : T.bark,
        border: `1px solid ${active ? (color || T.esp) : T.linen}`,
        borderRadius: 20,
        padding: "6px 14px",
        fontFamily: F.sans,
        fontSize: 12,
        fontWeight: active ? 700 : 500,
        cursor: "pointer",
        transition: "all .2s",
        whiteSpace: "nowrap",
      }}
    >
      {label}
    </button>
  );
}

// ── Spinner ───────────────────────────────────────────────────────
export function Spinner({ size = 24, color = T.gold }: { size?: number; color?: string }) {
  return (
    <div style={{
      width: size, height: size, borderRadius: "50%",
      border: `2px solid ${color}30`,
      borderTop: `2px solid ${color}`,
      animation: "spin 0.8s linear infinite",
    }} />
  );
}

// ── AIBadge ───────────────────────────────────────────────────────
export function AIBadge({ label = "Generated by Nora" }: { label?: string }) {
  return (
    <div style={{
      display: "inline-flex", alignItems: "center", gap: 5,
      background: T.goldP, border: `1px solid ${T.gold}40`,
      borderRadius: 20, padding: "3px 10px",
    }}>
      <span style={{ fontSize: 10 }}>✦</span>
      <span style={{ fontFamily: F.sans, fontSize: 10, fontWeight: 600, color: T.gold, letterSpacing: "0.08em" }}>
        {label}
      </span>
    </div>
  );
}

// ── NoraCallout ───────────────────────────────────────────────────
export function NoraCallout({
  message,
  eyebrow = "NORA NOTICED",
}: {
  message: string;
  eyebrow?: string;
}) {
  return (
    <div style={{
      background: `linear-gradient(135deg, ${T.esp}08, ${T.gold}08)`,
      border: `1px solid ${T.gold}30`,
      borderRadius: 16, padding: "14px 16px", marginBottom: 12,
    }}>
      <p style={{ fontFamily: F.sans, fontSize: 9, fontWeight: 700, letterSpacing: "0.16em", textTransform: "uppercase", color: T.gold, margin: "0 0 5px" }}>
        ✦ {eyebrow}
      </p>
      <p style={{ fontFamily: F.sans, fontSize: 13, color: T.esp, margin: 0, lineHeight: 1.6 }}>
        {message}
      </p>
    </div>
  );
}

// ── Input ─────────────────────────────────────────────────────────
export function Input({
  value,
  onChange,
  placeholder,
  type = "text",
  style,
}: {
  value: string;
  onChange: (v: string) => void;
  placeholder?: string;
  type?: string;
  style?: React.CSSProperties;
}) {
  return (
    <input
      type={type}
      value={value}
      onChange={(e) => onChange(e.target.value)}
      placeholder={placeholder}
      style={{
        width: "100%",
        background: T.ivory,
        border: `1.5px solid ${T.linen}`,
        borderRadius: 12,
        padding: "12px 14px",
        fontFamily: F.sans,
        fontSize: 16, // 16px prevents iOS zoom on focus
        color: T.esp,
        outline: "none",
        boxSizing: "border-box",
        WebkitAppearance: "none",
        ...style,
      }}
    />
  );
}

// ── Button ────────────────────────────────────────────────────────
export function Button({
  children,
  onClick,
  variant = "primary",
  disabled,
  style,
}: {
  children: React.ReactNode;
  onClick?: () => void;
  variant?: "primary" | "secondary" | "ghost" | "gold";
  disabled?: boolean;
  style?: React.CSSProperties;
}) {
  const styles: Record<string, React.CSSProperties> = {
    primary:   { background: T.esp, color: "#fff", border: "none" },
    secondary: { background: T.sand, color: T.esp, border: `1px solid ${T.linen}` },
    ghost:     { background: "none", color: T.bark, border: `1px solid ${T.linen}` },
    gold:      { background: `linear-gradient(135deg, ${T.gold}, #a88420)`, color: "#fff", border: "none" },
  };

  return (
    <button
      onClick={onClick}
      disabled={disabled}
      style={{
        ...styles[variant],
        borderRadius: 14,
        padding: "14px 20px",
        fontFamily: F.sans,
        fontSize: 14,
        fontWeight: 600,
        cursor: disabled ? "not-allowed" : "pointer",
        opacity: disabled ? 0.5 : 1,
        transition: "all .2s",
        width: "100%",
        minHeight: 48,
        touchAction: "manipulation",
        WebkitTapHighlightColor: "transparent",
        ...style,
      }}
    >
      {children}
    </button>
  );
}

// ── ProgressBar ───────────────────────────────────────────────────
export function ProgressBar({
  value,
  max = 100,
  color = T.gold,
  height = 6,
}: {
  value: number;
  max?: number;
  color?: string;
  height?: number;
}) {
  const pct = Math.min((value / max) * 100, 100);
  return (
    <div style={{ background: `${color}20`, borderRadius: 99, height, overflow: "hidden" }}>
      <div style={{
        width: `${pct}%`, height: "100%",
        background: color, borderRadius: 99,
        transition: "width .6s cubic-bezier(.4,0,.2,1)",
      }} />
    </div>
  );
}

// ── AIErrorCard ───────────────────────────────────────────────────
export function AIErrorCard({
  message = "Something went wrong",
  onRetry,
}: {
  message?: string;
  onRetry: () => void;
}) {
  return (
    <div style={{
      background: T.ivory, border: `1.5px solid ${T.linen}`,
      borderRadius: 20, padding: "24px 20px", textAlign: "center", marginBottom: 12,
    }}>
      <p style={{ fontFamily: F.serif, fontSize: 16, fontStyle: "italic", color: T.taupe, margin: "0 0 6px" }}>✦</p>
      <p style={{ fontFamily: F.sans, fontSize: 13, color: T.taupe, margin: "0 0 16px", lineHeight: 1.6 }}>{message}</p>
      <button onClick={onRetry} style={{
        background: T.esp, color: "#fff", border: "none", borderRadius: 12,
        padding: "10px 24px", fontFamily: F.sans, fontSize: 13, fontWeight: 600,
        cursor: "pointer", minHeight: 40, touchAction: "manipulation",
      }}>
        Try again
      </button>
    </div>
  );
}
